from selenium import webdriver

from base_pkg.all_methods import baseClass
driver = webdriver.Chrome(executable_path=r"C:\Users\sony\PycharmProjects\SeleniumTestProj\Drivers\chromedriver.exe")
b=baseClass()
b.feach_browser()
url="https://www.amazon.in"
b.feach_url(url)
c_url=b.current_url()
print("url is ",c_url)
url_title=b.url_title()
print("Title is",url_title)
w_element=driver.find_element_by_id("email")
b.mouseOver(w_element)
b.click()
b.mouseOver()
b.r_click()
b.print_capital(key_name="SHIFT",input_txt="abcdef")
b.click_and_hold(src="src_box",dest="dest_box")
b.switch_to_alert()
b.alert_accept()
b.alert_dismiss()
alt_text=b.get_text_frm_alert()
print(alt_text)
b.send_text_to_alert(alert_text="adssfghfjf")
b.switch_to_frame()
win_ids=b.all_open_windows()
b.switch_to_window(win_id=win_ids[1])
par_id=b.current_window()
b.close_current_window()
b.close_all_driver_win()
